exams/apps/teachers/urls.py
app_name = "teachers"
from django.urls import path
from .views import (TestListView, TestCreateView, TestUpdateView,
                    TestResultsView, TestDeleteView, QuestionDeleteView,
                    question_add, question_change)

urlpatterns = [
    path('', TestListView.as_view(), name='test_change_list'),
    path('test/add/', TestCreateView.as_view(), name='test_add'),
    path('test/<int:pk>/', TestUpdateView.as_view(), name='test_change'),
    path('test/<int:pk>/delete/', TestDeleteView.as_view(),
         name='test_delete'),
    path('test/<int:pk>/results/', TestResultsView.as_view(),
         name='test_results'),
    path('test/<int:pk>/question/add/', question_add, name='question_add'),
    path('test/<int:test_pk>/question/<int:question_pk>/', question_change,
         name='question_change'),
    path('test/<int:test_pk>/question/<int:question_pk>/delete/',
         QuestionDeleteView.as_view(), name='question_delete'),
]

exams/exams/urls.py
app_name = 'apps'
from django.contrib import admin
from django.urls import path, include, re_path
from apps.views import home, SignUpView
from apps.teachers.views import TeacherSignUpView
from apps.students.views import StudentSignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home_page'),
    re_path(r'^teachers/', include('apps.teachers.urls', namespace="teachers")),
    re_path(r'^students/', include('apps.students.urls', namespace="students")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/signup/student/', StudentSignUpView.as_view(),
         name='student_signup'),
    path('accounts/signup/teacher/', TeacherSignUpView.as_view(),
         name='teacher_signup'),
]

exams/apps/teachers/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from ..forms import BaseAnswerInlineFormSet, QuestionForm, TeacherSignUpForm
from ..models import Answer, Question, Test, User


class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:test_change_list')


@method_decorator([login_required],name='dispatch')
class TestListView(ListView):
    model = Test
    ordering = ('name', )
    context_object_name = 'tests'
    template_name = 'teachers/test_change_list.html'

    def get_queryset(self):
        queryset = self.request.user.tests \
            .annotate(questions_count=Count('questions', distinct=True)) \
            .annotate(taken_count=Count('taken_tests', distinct=True))
        return queryset


@method_decorator([login_required],name='dispatch')
class TestCreateView(CreateView):
    model = Test
    fields = ('name','pass_percentage')
    template_name = 'teachers/test_add_form.html'

    def form_valid(self, form):
        test = form.save(commit=False)
        test.owner = self.request.user
        test.save()
        messages.success(self.request, 'The test was created with success! Go ahead and add some questions now.')
        return redirect('teachers:test_change', test.pk)


# @method_decorator([login_required, teacher_required], name='dispatch')
class TestUpdateView(UpdateView):
    model = Test
    fields = ('name',)
    context_object_name = 'test'
    template_name = 'teachers/test_change_form.html'

    def get_context_data(self, **kwargs):
        kwargs['questions'] = self.get_object().questions.annotate(answers_count=Count('answers'))
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing tests that belongs
        to the logged in user.
        '''
        return self.request.user.tests.all()

    def get_success_url(self):
        return reverse('teachers:test_change', kwargs={'pk': self.object.pk})


@method_decorator([login_required],name='dispatch')
class TestDeleteView(DeleteView):
    model = Test
    context_object_name = 'test'
    template_name = 'teachers/test_delete_confirm.html'
    success_url = reverse_lazy('teachers:test_change_list')

    def delete(self, request, *args, **kwargs):
        test = self.get_object()
        messages.success(request, 'The test %s was deleted with success!' %
                         test.name)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.tests.all()


@method_decorator([login_required],name='dispatch')
class TestResultsView(DetailView):
    model = Test
    context_object_name = 'test'
    template_name = 'teachers/test_results.html'

    def get_context_data(self, **kwargs):
        test = self.get_object()
        taken_tests = test.taken_tests.select_related('student__user').order_by(
            '-date')
        total_taken_tests = taken_tests.count()
        test_score = test.taken_tests.aggregate(average_score=Avg('score'))
        extra_context = {
            'taken_tests': taken_tests,
            'total_taken_tests': total_taken_tests,
            'test_score': test_score
        }
        kwargs.update(extra_context)
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        return self.request.user.tests.all()


@login_required
def question_add(request, pk):
    # By filtering the test by the url keyword argument `pk` and
    # by the owner, which is the logged in user, we are protecting
    # this view at the object-level. Meaning only the owner of
    # test will be able to add questions to it.
    test = get_object_or_404(Test, pk=pk, owner=request.user)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.test = test
            question.save()
            messages.success(request, 'You may now add answers/options to the question.')
            return redirect('teachers:question_change', test.pk, question.pk)
    else:
        form = QuestionForm()

    return render(request, 'teachers/question_add_form.html',
                  {'test': test, 'form': form})


@login_required
def question_change(request, test_pk, question_pk):
    # This view is managing the permissions at object-level. By querying both
    # `test` and `question` we are making sure only the owner of the test can
    # change its details and also only questions that belongs to this
    # specific test can be changed via this url (in cases where the
    # user might have forged/player with the url params.
    test = get_object_or_404(Test, pk=test_pk, owner=request.user)
    question = get_object_or_404(Question, pk=question_pk, test=test)

    AnswerFormSet = inlineformset_factory(
        Question,  # parent model
        Answer,  # base model
        formset=BaseAnswerInlineFormSet,
        fields=('text', 'is_correct'), # Field to be displayed as inline form
        min_num=2, # Minimum number of forms should be filled by the user.
        validate_min=True, # If minimum number of forms not filled raise error
        max_num=4, # Maximum number of forms displayed and should be filled by
        # the user.
        validate_max=True # If maximum number of forms not filled raise error
    )

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        formset = AnswerFormSet(request.POST, instance=question)
        if form.is_valid() and formset.is_valid():
            with transaction.atomic():
                form.save()
                formset.save()
            messages.success(request, 'Question and answers saved with success!')
            return redirect('teachers:test_change', test.pk)
    else:
        form = QuestionForm(instance=question)
        formset = AnswerFormSet(instance=question)

    return render(request, 'teachers/question_change_form.html', {
        'test': test,
        'question': question,
        'form': form,
        'formset': formset
    })


@method_decorator([login_required], name='dispatch')
class QuestionDeleteView(DeleteView):
    model = Question
    context_object_name = 'question'
    template_name = 'teachers/question_delete_confirm.html'
    pk_url_kwarg = 'question_pk'

    def get_context_data(self, **kwargs):
        question = self.get_object()
        kwargs['test'] = question.test
        return super().get_context_data(**kwargs)

    def delete(self, request, *args, **kwargs):
        question = self.get_object()
        messages.success(request, 'The question %s was deleted with success!' % question.text)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return Question.objects.filter(test__owner=self.request.user)

    def get_success_url(self):
        question = self.get_object()
        return reverse('teachers:test_change', kwargs={'pk': question.test_id})

exams/templates/teachers/question_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change' test.pk %}">{{ test.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new question</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new question</h2>
  <p class="lead">First add text of the question. In the next step you will be able to add the answers choices.</p>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Save</button>
    <a href="{% url 'teachers:test_change' test.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
  </form>
{% endblock %}

exams/templates/teachers/question_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags crispy_forms_filters %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change' test.pk %}">{{ test.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ question.text }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ question.txt }}</h2>
  <form method="post" novalidate>
    {% csrf_token %}
    {{ formset.management_form }}
    {{ form|crispy }}
    <div class="card mb-3{% if formset.errors %} border-danger{% endif %}">
      <div class="card-header">
        <div class="row">
          <div class="col-8">
            <strong>Answers</strong>
          </div>
          <div class="col-2">
            <strong>Correct?</strong>
          </div>
          <div class="col-2">
            <strong>Delete?</strong>
          </div>
        </div>
      </div>
      {% for error in formset.non_form_errors %}
        <div class="card-body bg-danger border-danger text-white py-2">{{ error }}</div>
      {% endfor %}
      <div class="list-group list-group-flush list-group-formset">
        {% for form in formset %}
          <div class="list-group-item">
            <div class="row">
              <div class="col-8">
                {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                {{ form.text|as_crispy_field }}
                {% if form.instance.pk and form.text.value != form.instance.text %}<p class="mb-0 mt-1"><small class="text-muted font-italic"><strong>Old answer:</strong> {{ form.instance.text }}</small></p>{% endif %}
              </div>
              <div class="col-2">
                {{ form.is_correct }}
              </div>
              <div class="col-2">
                {% if form.instance.pk %}
                  {{ form.DELETE }}
                {% endif %}
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <p>
      <small class="form-text text-muted">Your question may have at least <strong>2</strong> answers and maximum <strong>4</strong> answers. Select at least one correct answer.</small>
    </p>
    <button type="submit" class="btn btn-success">Save changes</button>
    <a href="{% url 'teachers:test_change' test.pk %}" class="btn btn-outline-secondary" role="button">Cancel</a>
    <a href="{% url 'teachers:question_delete' test.pk question.pk %}" class="btn btn-danger float-right">Delete</a>
  </form>
{% endblock %}

exams/templates/teachers/question_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:question_change' quiz.pk question.pk %}">{{ question.text }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the question <strong>"{{ question.text }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:question_change' quiz.pk question.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}

exams/templates/teachers/quiz_delete_confirm.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change_list' %}">My Quizzes</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:quiz_change' quiz.pk %}">{{ quiz.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Confirm deletion</li>
    </ol>
  </nav>
  <h2 class="mb-3">Confirm deletion</h2>
  <p class="lead">Are you sure you want to delete the quiz <strong>"{{ quiz.name }}"</strong>? There is no going back.</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-lg">Yes, I'm sure</button>
    <a href="{% url 'teachers:quiz_change' quiz.pk %}" class="btn btn-outline-secondary btn-lg" role="button">Nevermind</a>
  </form>
{% endblock %}

exams/templates/teachers/test_add_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item active" aria-current="page">Add a new test</li>
    </ol>
  </nav>
  <h2 class="mb-3">Add a new test</h2>
  <div class="row">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save</button>
        <a href="{% url 'teachers:test_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
      </form>
    </div>
  </div>
{% endblock %}

exams/templates/teachers/test_change_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ test.name }}</li>
    </ol>
  </nav>
  <h2 class="mb-3">
    {{ test.name }}
    <a href="{% url 'teachers:test_results' test.pk %}" class="btn btn-primary float-right">View results</a>
  </h2>
  <div class="row mb-3">
    <div class="col-md-6 col-sm-8 col-12">
      <form method="post" novalidate>
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Save changes</button>
        <a href="{% url 'teachers:test_change_list' %}" class="btn btn-outline-secondary" role="button">Cancel</a>
        <a href="{% url 'teachers:test_delete' test.pk %}" class="btn btn-danger float-right">Delete</a>
      </form>
    </div>
  </div>
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-10">
          <strong>Questions</strong>
        </div>
        <div class="col-2">
          <strong>Answers</strong>
        </div>
      </div>
    </div>
    <div class="list-group list-group-flush list-group-formset">
      {% for question in questions %}
        <div class="list-group-item">
          <div class="row">
            <div class="col-10">
              <a href="{% url 'teachers:question_change' test.pk question.pk %}">{{ question.text }}</a>
            </div>
            <div class="col-2">
              {{ question.answers_count }}
            </div>
          </div>
        </div>
      {% empty %}
        <div class="list-group-item text-center">
          <p class="text-muted font-italic mb-0">You haven't created any questions yet. Go ahead and <a href="{% url 'teachers:question_add' test.pk %}">add the first question</a>.</p>
        </div>
      {% endfor %}
    </div>
    <div class="card-footer">
      <a href="{% url 'teachers:question_add' test.pk %}" class="btn btn-primary btn-sm">Add question</a>
    </div>
  </div>
{% endblock %}

exams/templates/teachers/test_change_list.html
{% extends 'base.html' %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page">My Tests</li>
    </ol>
  </nav>
  <h2 class="mb-3">My Tests</h2>
  <a href="{% url 'teachers:test_add' %}" class="btn btn-primary mb-3" role="button">Add test</a>
  <div class="card">
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Test</th>
          <th>Questions</th>
          <th>Students Attempted</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for test in tests %}
          <tr>
            <td class="align-middle"><a href="{% url 'teachers:test_change' test.pk %}">{{ test.name }}</a></td>
            <td class="align-middle">{{ test.questions_count }}</td>
            <td class="align-middle">{{ test.taken_count }}</td>
            <td class="text-right">
              <a href="{% url 'teachers:test_results' test.pk %}" class="btn btn-primary">View results</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="5">You haven't created any test yet.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

exams/templates/teachers/test_results.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change_list' %}">My Tests</a></li>
      <li class="breadcrumb-item"><a href="{% url 'teachers:test_change' test.pk %}">{{ test.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">Results</li>
    </ol>
  </nav>
  <h2 class="mb-3">{{ test.name }} Results</h2>

  <div class="card">
    <div class="card-header">
      <strong>Taken Quizzes</strong>
      <span class="badge badge-pill badge-primary float-right">Average Score: {{ test_score.average_score|default_if_none:0.0 }}</span>
    </div>
    <table class="table mb-0">
      <thead>
        <tr>
          <th>Student</th>
          <th>Date</th>
          <th>Score</th>
        </tr>
      </thead>
      <tbody>
        {% for taken_test in taken_tests %}
          <tr>
            <td>{{ taken_test.student.user.username }}</td>
            <td>{{ taken_test.date|naturaltime }}</td>
            <td>{{ taken_test.score }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="card-footer text-muted">
      Total respondents: <strong>{{ total_taken_tests }}</strong>
    </div>
  </div>
{% endblock %}